In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset = pd.read_csv('Market_Basket.csv')
dataset

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
list_data = dataset.values.tolist()

list_data[:5]

[['burgers',
  'meatballs',
  'eggs',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 ['chutney',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 ['turkey',
  'avocado',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 ['mineral water',
  'milk',
  'energy bar',
  'whole wheat rice',
  'green tea',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 ['low fat yogurt',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan]]

In [12]:
cleaned_list = []
temp = []
for i in list_data:
    for j in i:
        if str(j) != 'nan':
            temp.append(j)

    cleaned_list.append(temp)
    temp = []

cleaned_list[:10]

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food']]

# Training Apriori Model

In [7]:
#!pip install apyori

In [8]:
from apyori import apriori

rules = apriori(transactions=cleaned_list, min_support=0.04, min_confidence=0.002,min_length=1)
result = list(rules)

In [14]:
result[:10]

[RelationRecord(items=frozenset({'burgers'}), support=0.0872, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers'}), confidence=0.0872, lift=1.0)]),
 RelationRecord(items=frozenset({'cake'}), support=0.08106666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cake'}), confidence=0.08106666666666666, lift=1.0)]),
 RelationRecord(items=frozenset({'champagne'}), support=0.0468, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'champagne'}), confidence=0.0468, lift=1.0)]),
 RelationRecord(items=frozenset({'chicken'}), support=0.06, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chicken'}), confidence=0.06, lift=1.0)]),
 RelationRecord(items=frozenset({'chocolate'}), support=0.16386666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chocolate'}), confidence=0.16386666666666666, lift=1.0)]),
 RelationRecord(items=frozenset({'cookies'}), support=0.0804, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cookies'}), confidence=0.0804, lift=1.0)]),
 RelationRecord(items=frozenset({'cooking oil'}), support=0.05106666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cooking oil'}), confidence=0.05106666666666667, lift=1.0)]),
 RelationRecord(items=frozenset({'eggs'}), support=0.17973333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'eggs'}), confidence=0.17973333333333333, lift=1.0)]),
 RelationRecord(items=frozenset({'escalope'}), support=0.07933333333333334, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'escalope'}), confidence=0.07933333333333334, lift=1.0)]),
 RelationRecord(items=frozenset({'french fries'}), support=0.17093333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'french fries'}), confidence=0.17093333333333333, lift=1.0)])]

# Creating dataframe for:
item_set, support, lift, confidence

In [10]:
result_list = []
for items in result:
    temp_list = []
    temp_list.append(items[0]) # Frozen-set
    temp_list.append(items[1]) # Support

    temp_list.append(items[2][0][2]) # Confidence
    temp_list.append(items[2][0][3]) # Lift

    result_list.append(temp_list)

result_df = pd.DataFrame(result_list, columns=['Set', 'Support', 'Confidence', 'Lift'])

In [11]:
result_df

                             Set   Support  Confidence  Lift
0                      (burgers)  0.087200    0.087200   1.0
1                         (cake)  0.081067    0.081067   1.0
2                    (champagne)  0.046800    0.046800   1.0
3                      (chicken)  0.060000    0.060000   1.0
4                    (chocolate)  0.163867    0.163867   1.0
5                      (cookies)  0.080400    0.080400   1.0
6                  (cooking oil)  0.051067    0.051067   1.0
7                         (eggs)  0.179733    0.179733   1.0
8                     (escalope)  0.079333    0.079333   1.0
9                 (french fries)  0.170933    0.170933   1.0
10                 (fresh bread)  0.043067    0.043067   1.0
11             (frozen smoothie)  0.063200    0.063200   1.0
12           (frozen vegetables)  0.095333    0.095333   1.0
13               (grated cheese)  0.052400    0.052400   1.0
14                   (green tea)  0.132000    0.132000   1.0
15                 (ground beef)  0.098267    0.098267   1.0
16               (herb & pepper)  0.049467    0.049467   1.0
17                       (honey)  0.047333    0.047333   1.0
18              (low fat yogurt)  0.076400    0.076400   1.0
19                        (milk)  0.129600    0.129600   1.0
20               (mineral water)  0.238267    0.238267   1.0
21                   (olive oil)  0.065733    0.065733   1.0
22                    (pancakes)  0.095067    0.095067   1.0
23                      (salmon)  0.042400    0.042400   1.0
24                      (shrimp)  0.071333    0.071333   1.0
25                        (soup)  0.050533    0.050533   1.0
26                   (spaghetti)  0.174133    0.174133   1.0
27                    (tomatoes)  0.068400    0.068400   1.0
28                      (turkey)  0.062533    0.062533   1.0
29            (whole wheat rice)  0.058533    0.058533   1.0
30    (chocolate, mineral water)  0.052667    0.052667   1.0
31         (mineral water, eggs)  0.050933    0.050933   1.0
32  (mineral water, ground beef)  0.040933    0.040933   1.0
33         (mineral water, milk)  0.048000    0.048000   1.0
34    (mineral water, spaghetti)  0.059733    0.059733   1.0